language: "python"
python:
   - "2.6"
   - "2.7"
   - "3.2"
   - "3.3"
   - "3.4"
   - "pypy"
   - "pypy3"
install:
  - pip install hacking flake8 flake8-import-order flake8-pep257
script:
  - ./tools/run_linter.sh
